### ISSUE TITLE
Consolidate oscilloscope servers

### ISSUE THREAD

**Issue by DanielSank** [martinisgroup/servers#10]
There are as many oscilloscope servers as there are oscilloscope models, which is ridiculous. There should be a common interface provided by single serve which produces the appropriate command strings for each model of scope.

**Comment by pomalley** [comment]
Dan what's the status here? I'm going on a branch-merging-and/or-deleting binge and trying to figure out what's what.

**Comment by DanielSank** [comment]
I consolidated 95% of the oscilloscope code into a single server with
different DeviceWrappers for each model. It needs to be tested, and some of
the more... interesting settings should be implemented (only 2 such
settings, I think).
