### ISSUE TITLE
MKS server and web log aren't playing nice

### ISSUE THREAD

**Issue by zchen088** [martinisgroup/servers#105]
![image](https://cloud.githubusercontent.com/assets/10439313/7218187/37ea6196-e614-11e4-8160-b0b925b0d0f8.png)

**Comment by jwenner** [comment]
It looks like the web log is looking for "MKS Gauge Server Testhack" (yes, Vince used to use this well-named server), when the fridge is running "MKS Gauge Server".

**Comment by pomalley** [comment]
I'm pretty sure these days they call a "web log" just a "blog". :-)

**Comment by DanielSank** [comment]
rekt
