### ISSUE TITLE
dac convolution server hard coded to read config data from Vince registry

### ISSUE THREAD

**Issue by DanielSank** [martinisgroup/servers#107]
[This is clearly broken](https://github.com/martinisgroup/servers/commit/9e186a6a9e78c0e87bc017ed1a0ccb59fa06894d#diff-910b6ccaacbc7204b89afa4bccefc972R46).

**Comment by jwenner** [comment]
@DanielSank, should this issue be closed?

**Comment by DanielSank** [comment]
Yes.
