### ISSUE TITLE
PR incoming for the jump table stuff

### ISSUE THREAD

**Issue by pomalley** [martinisgroup/servers#119]
As we discussed elsewhere, I'm going to be breaking up the u/pomalley/jump-table2 branch into a series of smaller diffs, in preparation for code review. If you've got anything to say about any of the files touched by this branch, speak now or forever hold your peace! (Does anyone ever actually "speak now", outside of movies?)

The first step is (probably) going to be rebasing this off master and force-pushing, so this will likely invalidate anyone's cloned version of this branch. Sorry.

**Comment by pomalley** [comment]
The PR's have been created. See #122 and #123.

**Comment by DanielSank** [comment]
:star: Yayayayay :star:

**Comment by jwenner** [comment]
Settings 1300 and 1301 (DAC Bringup and DAC Bringup New) have the same function name.

**Comment by jwenner** [comment]
Ignore the most recent comment. Meant to put it on the PR, not the issue.

**Comment by pomalley** [comment]
This has been merged. Thanks everyone for the reviews!
