### ISSUE TITLE
The FPGA server and associated tools should support the jump table

### ISSUE THREAD

**Issue by DanielSank** [martinisgroup/servers#12]
The order of things to do here is roughly

1. Test jump table with fpgaTest (from pyle) to make sure the FPGA works as advertised.
2. Write DAC subclasses for the jump table build and add necessary settings to the server. This step should be simple as only a few parts of the interface have changed.
3. Update qubit sequencer. This should probably be its own ticket to be created when work on the FPGA server is done.

When this is complete a new set of tickets should be generated in pyle specifying how fpgaseq and the gatecompiler will be modified.

**Comment by pomalley** [comment]
What are we going to do about backwards compatibility, i.e. non-jump-table boards?

Mostly I mean for the code base: I can't imagine a situation where you have JT boards and non-JT boards in the same experiment. But there's a whole lot of code (i.e. dual block stuff) that can simply be axed once we get the jump table working. And it would be good (not to mention cathartic) to axe it. But do we want to branch the code until everyone finishes their current experiment? (Probably not.)

**Comment by DanielSank** [comment]
Branch the code _for jump table related changes_. We need to exercise some discipline here and not dump other commits into the same branch.

**Comment by pomalley** [comment]
Done!
