### ISSUE TITLE
fpga.jump_table_add_entry signature unclear

### ISSUE THREAD

**Issue by bmyersq** [martinisgroup/servers#147]
(Dan writing here)

It's really  hard to tell from the LabRAD docstring for `jump_table_add_entry` what the second argument is supposed to be for each op code. I might be helpful to just tabulate this right in the docstring. Another option is to break these into individual settings, but I think we already discussed and decided not to do that. In any case, clearer instructions needed.

@pomalley

**Comment by DanielSank** [comment]
Fixed this in latest round of changes to `jt-fpga-server` branch, and merge to master is incoming.
