### ISSUE TITLE
Specify whether or not jump table is cleared after "Run Sequence"

### ISSUE THREAD

**Issue by bmyersq** [martinisgroup/servers#148]
There's a jump table clear command, but is it allowed to *not* clear between invocations of `run_sequence`? What's the expected use here?

**Comment by DanielSank** [comment]
This is now explained in the fpga server's documentation and the PR is approved (well, by at least me). Since I actually filed this issue I'm going to take the liberty of closing it now. If this someone disagrees just re-open.
