### ISSUE TITLE
Convert Qubit Server to scala

### ISSUE THREAD

**Issue by maffoo** [martinisgroup/servers#164]
We'd like to convert the qubit server to scala, to consolidate on a single JVM language and to take advantage of the performance improvements in the scalabrad api. Because this is a big change, we'll be taking it in stages, and will use this issue to track the overall progress. The plan is roughly as follows:

1. Translate chunks of files from java to scala. Doing this in chunks will keep the size of reviews small, and also allow us to maintain a working system at each stage. Because we'll be interoperating with java and scala, we won't be able to use a lot of the scala goodies. This will be a good thing, because we'll limit the changes to a very basic transliteration between the language, which will help people get used to reading scala. This will mean that the scala code may look awkward, but trust me, it gets better :)
2. Once everything is in scala, we can add in some of the scala goodies to simplify the code, use scala collections, etc. Again, we'll do this in small chunks so that reviews are manageable. Hopefully here some of the advantages of scala will start to become clear.
3. Convert from jlabrad to scalabrad. The scalabrad api will feel much more scala-y than the jlabrad api, so we'll be able to get rid of the remaining javaisms at this point and really clean up the code.

**Comment by jwenner** [comment]
@maffoo, with #250 in, does this mean that this issue can be closed?

**Comment by maffoo** [comment]
Yup, thanks @jwenner!
