### ISSUE TITLE
New Version of Visa (GPIB software) notes

### ISSUE THREAD

**Issue by andrewdunsworth** [martinisgroup/servers#20]
You are now required to put '::INSTR' at the end of names to GPIB devices or they will not be recognized...

**Comment by BernardoGO** [comment]
@andrewdunsworth 
Are you being able to connect with the ::INSTR?

**Comment by Sharpe23** [comment]
@BernardoGO @andrewdunsworth 
its not working for me with it

**Comment by pomalley** [comment]
What version of pyvisa are you guys using? It should work with whatever string is returned from the query instruments list function, I think it's something like `visa.ResourceManager().list_resources()`.
