### ISSUE TITLE
Remove poor language from qubit sequencer

### ISSUE THREAD

**Issue by jwenner** [martinisgroup/servers#207]
There is an improper 4-letter word in the qubit sequencer server at https://github.com/martinisgroup/servers/blob/4cd4b3cd7f3144f55daa6e05eb355052b02d783e/QubitServer/src/main/java/org/labrad/qubits/QubitServer.java#L119. Since I don't know java, could someone please take care of this? Perhaps @maffoo in the course of #164? Thanks.

**Comment by DanielSank** [comment]
@jwenner I don't think you need to know java to change a few characters in a line comment :-)
