### ISSUE TITLE
ADR GUI scrolling up / move it to servers / add me to pyle

### ISSUE THREAD

**Issue by andrewdunsworth** [martinisgroup/servers#21]
Peter.

**Comment by DanielSank** [comment]
Shouldn't this be three issues?

On Fri, Jan 9, 2015 at 8:53 AM, andrewdunsworth <notifications@github.com>
wrote:

> Peter.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/martinisgroup/servers/issues/21>.
>



-- 
Daniel Sank

**Comment by andrewdunsworth** [comment]
Yes, it should, but they're all for me (peter) to do so I told him to do this.

--peter on andrew's account

**Comment by andrewdunsworth** [comment]
Did you happen to fix the auto scrolling of the check boxes?

**Comment by pomalley** [comment]
No, not yet, but if you want to move the ADR GUI folder over you can follow these instructions:

http://gbayer.com/development/moving-files-from-one-git-repository-to-another-preserving-history/

Might as well do the fridge guardian too, do you agree, @DanielSank?

**Comment by zchen088** [comment]
How are we differentiating which GUIs are in pyle and which are in servers?

**Comment by pomalley** [comment]
My thought was that the ones that essentially provide an interface to a server go in servers, and ones that are more related to data taking go in pyle.

**Comment by zchen088** [comment]
I don't think we have any GUIs that are related to data taking right now. Should we just move all of them to servers?

**Comment by pomalley** [comment]
Maybe the Wiring Editor?
