### ISSUE TITLE
What is that largest allowed value of counts for an ADC trigger table entry?

### ISSUE THREAD

**Issue by btchiaro** [martinisgroup/servers#211]
I don't understand the notation used in GHzAD_v7.md, but I believe my question is answered by the following line:
```
The value rcount[15..0] + 1 is the number of AD triggers per table entry. 
```
Does this mean that that each trigger table entry may have a count of up to 2**16 +1?

**Comment by ejeffrey** [comment]
The maximum is 2^16, not 2^16+1.  What the notation means is that If
rcount[15..0] == 0x0000, that entry will trigger once (0+1).  If
rcount[15..0] == 0x0001, the entry will trigger twice (1+1).  If
rcount[15..0] == 0xFFFF = 2^16-1, that entry will trigger 2^16 times.

Evan

**Comment by btchiaro** [comment]
Thanks @ejeffrey  This makes sense now.
