### ISSUE TITLE
VNA Server has a VISA timeout error when the number of VNA averages is too large

### ISSUE THREAD

**Issue by andrewdunsworth** [martinisgroup/servers#22]
It might also have to do with the sweep settings (such as number of points, and IF bandwidth).  

Here is the error report:

![image](https://cloud.githubusercontent.com/assets/8405285/5689469/34d1bba0-981a-11e4-9597-ddba7e070b3c.png)

**Comment by pomalley** [comment]
1) What server function causes this?
2) In that function, what are the GPIB commands being sent?

**Comment by andrewdunsworth** [comment]
I'm pretty sure this has to do with sending data to the datavault actually.

**Comment by andrewdunsworth** [comment]
I think it is where it is trying to save it hangs and the timeout is just a symptom of this.

**Comment by andrewdunsworth** [comment]
A problem seems to occur in a call to pyle.plotting.dstools.getDataset

**Comment by pomalley** [comment]
I'm not sure how this causes a VISA timeout, but if you can't load a dataset then that is certainly a problem.

**Comment by andrewdunsworth** [comment]
It might be unrelated....

**Comment by andrewdunsworth** [comment]
Currently it seems you can get away with just doing one datavault average and this is my kludgey workaround.

**Comment by pomalley** [comment]
OK. I'm still not quite buying the fact that a data vault thing is causing a VISA timeout but if you have a workaround for now... I'll sit down with you at some point and we can figure this out.
