### ISSUE TITLE
Direct Ethernet server timeout errors contain overly-verbose stack trace

### ISSUE THREAD

**Issue by maffoo** [martinisgroup/servers#233]
In operations like "read" where timeouts are expected, the stack trace doesn't help, and in fact mostly just scares and confuses users. We should get rid of these stack traces. See #232 for an example.

**Comment by ejeffrey** [comment]
So this looks fine, but I don't understand it.  I get catching and throwing a new exception for timeouts to avoid including the whole stack trace on something that isn't exceptional, but why does replacing sys.error() with fail() improve things?
