### ISSUE TITLE
Document data vault signals

### ISSUE THREAD

**Issue by DanielSank** [martinisgroup/servers#254]
The [signals emitted by the data vault](https://github.com/martinisgroup/servers/commit/feaa1dfa85482db3f0ff39b202dede2c473705f3#diff-6c24bfa1375c5007a1c6f77b2f3f0979R27) are not documented. This caused user confusion in [pylabrad #187](https://github.com/labrad/pylabrad/issues/187).

**Comment by chrismacklin** [comment]
I would also really appreciate it if this documentation discussed (or at least pointed to) some of the details on, for example, how the context-specific messaging is achieved.
