### ISSUE TITLE
Document return signature of qubit sequencer's .run method

### ISSUE THREAD

**Issue by DanielSank** [martinisgroup/servers#262]
Talking to Jimmy just now, I learned that only a few people in the lab understand the return signature of this incredibly important method. Surprised, I looked at the LabRAD doc and found it's almost completely blank. This is likely responsible for a feeling of mystery surrounding how to process data returned by the sequencer. In Jimmy's own words: "I had no idea about the channels, states, demod thing until ..."

Not good :P

**Comment by btchiaro** [comment]
+1
