### ISSUE TITLE
Direct ethernet server warnings

### ISSUE THREAD

**Issue by zchen088** [martinisgroup/servers#267]
I'm installing the new redheatdos, and am getting these warnings when I start the direct ethernet server:
![image](https://cloud.githubusercontent.com/assets/10439313/11260760/df72c046-8e22-11e5-8f85-c314f494105c.png)
Is this a problem?

**Comment by maffoo** [comment]
not a problem; those messages are always printed and things work fine on other machines.

**Comment by DanielSank** [comment]
This should be documented in the readme or something. Having a bunch of warnings print out when one runs a piece of software is somewhat disconcerting :)

**Comment by maffoo** [comment]
See #270
