### ISSUE TITLE
Make ghz_dac_calibration command line instead of semi-gui

### ISSUE THREAD

**Issue by JulianSKelly** [martinisgroup/servers#28]

**Comment by DanielSank** [comment]
Really glad to see this broken up into small tasks :D

**Comment by JulianSKelly** [comment]
It was a good suggestion, things were getting ugly fast.

**Comment by DanielSank** [comment]
![teamwork](https://cloud.githubusercontent.com/assets/4584456/5994091/e63a7a36-aa1b-11e4-82e5-ca95882286fd.jpg)

**Comment by pomalley** [comment]
BOOM
