### ISSUE TITLE
Can I get older version of QubitServer?

### ISSUE THREAD

**Issue by Coxious** [martinisgroup/servers#295]
Hi,

The earliest version of Qubit Server Source code on github was wrote in 2014, and our system is currently running a qubit server compiled in 2012 May 12. Can I get the source code of Qubit Server of that version? 

Thanks a lot.

**Comment by DanielSank** [comment]
@pomalley is that still on skynet?

**Comment by jwenner** [comment]
@DanielSank, the old version appears to be in pyle (see https://github.com/martinisgroup/pyle/tree/0f35872c41526e8e4d2a26ba8f2a7aa0fbb0a737/dev/QubitServer - private link). So if you know how to package this...
