### ISSUE TITLE
Flattening error in fpga_test

### ISSUE THREAD

**Issue by BrooksCampbell** [martinisgroup/servers#349]
I get the following error when I use `do_cycle` [here](https://github.com/martinisgroup/servers/blob/master/fpgalib/fpga_test.py#L317):

`FlatteningError: (12345) Could not flatten ('CYCLE', (64, 40, 0, 0)) to ['s', '(
sww)', '(swww)', '(sw)', '(swwww)']. [payload=None]`

@JulianSKelly

**Comment by JulianSKelly** [comment]
Please list the fix when you close an issue.

**Comment by BrooksCampbell** [comment]
We updated pylabrad.
