### ISSUE TITLE
Refactor the jeebus out of the qubit sequencer

### ISSUE THREAD

**Issue by pomalley** [martinisgroup/servers#36]
There's a fair amount of cruft in there as it is, and many of the additions I made over the past couple years probably appear somewhat haphazard to the casual observer. After the jump table stuff is complete the qubit sequencer should be refactored.

**Comment by DanielSank** [comment]
But, but... the jeebus is what makes the qubit sequencer work!

**Comment by pomalley** [comment]
Oh, don't I know it.

**Comment by pomalley** [comment]
The qubit server is as refactored as it's going to be for now.
