### ISSUE TITLE
Improve Qt4 installation procedure

### ISSUE THREAD

**Issue by brooksfoxen** [martinisgroup/servers#372]
1. Don't need sudo anywhere.

1. Make virtualenv with `--always-copy`. Without this, your virtualenv's /include/python2.7 is a symlink to `/usr/include/python2.7`, which prevents the installers from working without sudo. You don't want to sudo because then you're putting stuff that should be in your virtualenv into a system directory.

1. Add `--incdir=/path/to/virtualenv/include/python2.7` when configuring sip.

1. Symlink from `/usr/include/python2.7/sip.h` --> `/path/to/virtualenv/include/python2.7/sip.h`

1. In general, check that make... to be continued....

**Comment by DanielSank** [comment]
See instructions [here](https://docs.google.com/document/d/1f_rZinhOOSVE_wjScR3jwJagt6MIqkIfthttmF7RWtk/edit). Everything works up to PyQwt, which fails for a reason I don't understand.
