### ISSUE TITLE
Deconvolution - Settling and Reflection rates and amplitudes seem incorrectly applied.

### ISSUE THREAD

**Issue by btchiaro** [martinisgroup/servers#383]
It appears as though settling amplitudes are being applied with the reflection rates.  It's possible that this output is correct and we don't fully understand the physics.  If so please advise.  Our data is below.
Running spectroscopy_z_func on master pyle, master servers, we observe the following pulses, where the magenta trace is the pulse to which the corrections should be applied:

Our control experiment has all amplitudes set to zero, so that there should be no compensation for settling times or reflections.
With parameters:
settlingRates:[0.1 GHz]
settlingAmplitudes:[0]
reflectionRates:[0.001 GHz]
reflectionAmplitudes:[0]
We observe:
![wp_20161025_15_13_29_pro](https://cloud.githubusercontent.com/assets/8885911/19706479/e088d5ae-9ac6-11e6-95bb-abbc95d21d6a.jpg)

Now we set a large reflection amplitude and do not observe a correction to the pulse.
With parameters:
settlingRates:[0.1 GHz]
settlingAmplitudes:[0]
reflectionRates:[0.001 GHz]
reflectionAmplitudes:[0.5]
We observe:
![wp_20161025_15_15_36_pro](https://cloud.githubusercontent.com/assets/8885911/19706481/e61fd1ac-9ac6-11e6-8d65-56f52aab6aa1.jpg)

If we turn on the settling amplitude, with the reflection amplitude set to zero, we observe what appears to be a reflection correction at a time that seems related to the reflection rate.
With:  
settlingRates:[0.1 GHz]
settlingAmplitudes:[0.5]
reflectionRates:[0.001 GHz]
reflectionAmplitudes:[0.0]
We observe:
![wp_20161025_15_16_39_pro](https://cloud.githubusercontent.com/assets/8885911/19706486/ec47dd54-9ac6-11e6-817c-3be1347f2c28.jpg)

We check this by halving the settling amplitude and see that the correction pulse is halved.
With:
settlingRates:[0.1 GHz]
settlingAmplitudes:[0.25]
reflectionRates:[0.001 GHz]
reflectionAmplitudes:[0.0]
We observe:
![wp_20161025_15_18_43_pro](https://cloud.githubusercontent.com/assets/8885911/19706496/f551f8a8-9ac6-11e6-8f16-bf23232d81a3.jpg)

By changing the reflection rate we are able to change the timing of the correction pulse.
With:
settlingRates:[0.1 GHz]
settlingAmplitudes:[0.25]
reflectionRates:[0.002 GHz]
reflectionAmplitudes:[0.0]
We observe:
![wp_20161025_15_19_54_pro](https://cloud.githubusercontent.com/assets/8885911/19706498/f7c6db76-9ac6-11e6-9fa7-a0df97ff73d7.jpg)

@zchen088 @maffoo @JulianSKelly @DanielSank 
Thanks!

**Comment by zchen088** [comment]
Ah yes, I found a typo.

**Comment by zchen088** [comment]
Note that this server actually lives in pyle, and I've fixed it there.

**Comment by btchiaro** [comment]
Thanks for the fix Jimmy! I'm pulling this now.
