### ISSUE TITLE
Can't get trace from scope.

### ISSUE THREAD

**Issue by andrewdunsworth** [martinisgroup/servers#386]
![image](https://cloud.githubusercontent.com/assets/8405285/20406921/2d1c6a84-acc4-11e6-82ad-19fe23eef92c.png)

**Comment by maffoo** [comment]
What version of pylabrad are you using on the computer where the server is running? The `read_raw` method was added in 0.96.1 (https://github.com/labrad/pylabrad/commit/b9067425ce1bddf9efa08638e89b0395e52fc52b).

**Comment by andrewdunsworth** [comment]
I just pulled master.

**Comment by andrewdunsworth** [comment]
On gordy.

**Comment by maffoo** [comment]
From the traceback, it looks like python was installed with pip (`C:\Python27\lib\site-packages\labrad\server.py`). You can check the version by calling `pip list` in a terminal windows and looking for the pylabrad entry. You can upgrade it with `pip install --upgrade pylabrad`.

**Comment by DanielSank** [comment]
I think Matthew means that pylabrad was installed with pip.

**Comment by maffoo** [comment]
Yes, thanks @DanielSank :-)

**Comment by DanielSank** [comment]
So... this went away?

**Comment by maffoo** [comment]
Yes, updating pylabrad fixed things. (This also required some futzing with the python path because windows.)
