### ISSUE TITLE
In pylabrad units, 'psi' is a constant, not a unit

### ISSUE THREAD

**Issue by mgiustina** [martinisgroup/servers#393]
Unit conversions between psi and anything else do not work, because 'psi' is included in pylabrad as a constant rather than a unit.

```
import labrad.units as U
U.psi
```
returns
`Value(6894.75729317, 'Pa')`

**Comment by maffoo** [comment]
Maybe file this issue against [pylabrad](https://github.com/labrad/pylabrad) instead; we'll have to fix it there.
