### ISSUE TITLE
ADR server log is named with a timestamp in the future

### ISSUE THREAD

**Issue by mgiustina** [martinisgroup/servers#404]
After restarting all ADR servers, a new ADR logfile is created, with a name like (e.g.) 00030 - ADR Log - 2017-01-18 17:41.
I would expect this timestamp to be the time at which the logfile was created, however it is a time in the future.

**Comment by maffoo** [comment]
Is the system clock set properly on the machine where the ADR server is running?

**Comment by ejeffrey** [comment]
How far in the future?  My guess is that the machine running the server
just has the clock set wrong, but it could be also using UTC instead of the
local timezone.

**Comment by mgiustina** [comment]
Sorry for the noise. Apparently the machine clock needs to be reset.
