### ISSUE TITLE
What is the 'Vince' branch and why is it the active branch on Trench?

### ISSUE THREAD

**Issue by DanielSank** [martinisgroup/servers#58]
I am very confused by this. Can someone who was doing experiments in Trench (in the trenches?) before the APS meeting give me a clue?

**Comment by pomalley** [comment]
Bump?

**Comment by DanielSank** [comment]
Badump.

**Comment by maffoo** [comment]
for the newbie, what is trench?

**Comment by DanielSank** [comment]
LabRAD managing computer on dry DR.

**Comment by maffoo** [comment]
ah, well I see a lot of @pomalley commits in the log for the branch that don't seem to be on master; maybe he can shed some light?

**Comment by pomalley** [comment]
Actually, those commits by me are cherry-picked from the old branches where I was working on the DR logger and SuperMonitor stuff. They should be in master at this point, I believe.

**Comment by pomalley** [comment]
It's the other commits I'm not sure about.

**Comment by jwenner** [comment]
The active branch on trench has been master for some time now.
