### ISSUE TITLE
FPGA server swallowing setup packets errors

### ISSUE THREAD

**Issue by pomalley** [martinisgroup/servers#59]
For some reason the exception raised here:

https://github.com/martinisgroup/servers/blob/master/GHzDACs/ghz_fpga_server.py#L815

is not getting propagated back to the user and instead things hang. I don't know why, but if I put in a print statement before I can see the message.

**Comment by pomalley** [comment]
Ugh, I got hit by this again today. I'd like to restate how friggin terrible this is.

**Comment by maffoo** [comment]
Can you tell which packet send is failing? It looks `sendAll` is invoked in three places, for [Load packets](src/main/scala/org/labrad/qubits/controller/MemoryController.scala), [Setup packets](https://github.com/martinisgroup/servers/blob/master/GHzDACs/ghz_fpga_server.py#L665), and [Read packets](https://github.com/martinisgroup/servers/blob/master/GHzDACs/ghz_fpga_server.py#L665). The case of Setup packets, the deferred returned by `sendAll` is being immediately yielded, but in the case of load and read, there are locking calls (runLock.acquire and readLock.release) happening between the call to `sendAll` and actually yielding to capture the results (or thrown exception). So, if either of those locking operations fails, then the exception could be swallowed. If we could determine which invoking was hanging, it could help narrow down what's happening.

**Comment by pomalley** [comment]
Both times so far it was the setup packets--specifically the setup packets for the DC rack server.

**Comment by pomalley** [comment]
I believe this has been fixed with the changes to error handling in the FPGA server.
