### ISSUE TITLE
Qubit Sequencer context hangs on to last error

### ISSUE THREAD

**Issue by JulianSKelly** [martinisgroup/servers#6]
When the qubit sequencer returns an error, e.g. conflicting microwave configurations, it will continue to return this error until a new python session is started. (context).

**Comment by maffoo** [comment]
This turned out to be a problem with the way pylabrad was dealing with futures across thread boundaries. Fixed in martinisgroup/pylabrad#86

**Comment by pomalley** [comment]
That has been merged to master so I'll close this issue.
