### ISSUE TITLE
Datavault undefined local variable

### ISSUE THREAD

**Issue by DanielSank** [martinisgroup/servers#61]
When trying to `cd` to an as-yet non-existing directory:

```python
exceptions.UnboundLocalError: local variable 'create' referenced before assignment
```

**Comment by ejeffrey** [comment]
This is fixed in git, but hasn't been pushed to skynet.  Since it is just
the wrong error message it doesn't seem like a high priority.

**Comment by ejeffrey** [comment]
Duplicate of #7
