### ISSUE TITLE
Serial server not able to talk to MKS gauges on Vince

### ISSUE THREAD

**Issue by zchen088** [martinisgroup/servers#62]
At some point on Thursday, MKS gauge server lost contact with the hardware. @JulianSKelly might know more about when/how this happened.

In debugging, we tried writing and reading via the NI MAX software, which worked and gave us the correct pressures. We were also successful using pyvisa. However, we couldn't seem to communicate with the gauges using pyserial. Does anyone know how pyserial and pyvisa interact with the gauges differently?

**Comment by pomalley** [comment]
I have updated the serial server and the DR logger in the branch
fixing-dr-logger. Try using that if you weren't already; I changed the
timeout from 0 to 0.01. Don't know why I needed to do that, though.

**Comment by JulianSKelly** [comment]
Cool that seemed to fix my problem. Me being Jimmy.

**Comment by pomalley** [comment]
Boom! Paternity leave, schmaternity leave.

**Comment by DanielSank** [comment]
How come so many people in the lab look like Julian?

**Comment by pomalley** [comment]
Also it would be awesome if someone could see about getting the
fix-dr-logger branch merged in, because I'm not sure when I'll be able to
get to it. It should tie in with the newer supermonitor to give you lots of
info about how the dr logger is failing (if it is).

**Comment by pomalley** [comment]
The MKS gauges on Vince are working now.
