### ISSUE TITLE
Supermonitor hangs on last value

### ISSUE THREAD

**Issue by JulianSKelly** [martinisgroup/servers#68]
Occasionally, the supermonitor will stop updating until restart.

**Comment by pomalley** [comment]
Latest version of supermonitor and dr logger? (I assume so, since AFAICT the PR's were merged.)
DR Logger still going (i.e. data still coming into the dataset (that you can see in the grapher)?
Any output in the console?

**Comment by pomalley** [comment]
As long as the servers keep running, the SuperMonitor seems to be working. If this problem crops up again we can re-open the issue.

**Comment by maffoo** [comment]
Supermonitor should keep working if servers restart. See #168.
