### ISSUE TITLE
DataVault multihead unbound local error

### ISSUE THREAD

**Issue by ejeffrey** [martinisgroup/servers#7]
Sometimes trying to do a datavault cd I get the following error:

  File "data_vault_multihead.py", line 1029, in cd
    if not Session.exists(temp) and not create:

**Comment by DanielSank** [comment]
bump

**Comment by ejeffrey** [comment]
Fixed in master, not pushed to skynet.

**Comment by maffoo** [comment]
are you bumping because you saw the error or because this is old? I think this was fixed a long time ago, but it may be that the server running on skynet has not been updated and restarted.

**Comment by maffoo** [comment]
Closing since this is fixed in master.
