### ISSUE TITLE
fpga.pll_init() returns labrad type error

### ISSUE THREAD

**Issue by rpbarnes** [martinisgroup/servers#75]
I'm currently using build 14 with GHzDAC_V8_B14_P22_P45_s15.sof loaded onto the fpga. I'm running python 2.7.9 on windows 7.

I use the 'jump_tables_bench_test branch' of servers repo.
I use up-to-date version of pylabrad, pulled from repository.
I run labrad, direct ethernet, and ghz_fpga_server.py (from jtbt branch). Screen shot of running programs below.

![lr_ghzs_de_aftercommand](https://cloud.githubusercontent.com/assets/5769539/6857609/3b5dd67a-d3c5-11e4-8f56-ba1fed9463df.PNG)

I then run the following code to initialize the fpga and get the type error.

![pythontraceback](https://cloud.githubusercontent.com/assets/5769539/6857587/faac4364-d3c4-11e4-846f-b1e730e99ee1.PNG)

I run the same lines from above in ipython and get a more detailed traceback.

![moreinformativeerrormessage](https://cloud.githubusercontent.com/assets/5769539/6857762/5b7fc6d8-d3c6-11e4-9cd4-c8b2614263c5.PNG)

I insert a print statement in ghz_fpga_server.py and run the code in ScreenShot2 and get a response on the server end, shown in screen shot below along with code to generate print statement.

![printstatementnewerror](https://cloud.githubusercontent.com/assets/5769539/6857650/a389652a-d3c5-11e4-83ee-3b26c2ae4e04.PNG)

Please let me know if you need anymore detail or if you're having trouble generating the error.

**Comment by pomalley** [comment]
The jump table stuff is still under heavy development. Appreciate the bug report, hope to fix it soon!

**Comment by rpbarnes** [comment]
Thanks! I've been conversing with Daniel as well. Do let me know if you 
need any help reproducing the error.
~Ryan

**Comment by DanielSank** [comment]
I don't think this is a jump table problem per se. It looks like something more basic broke in going to the updated code though.

**Comment by pomalley** [comment]
This should be fixed by 96cc31784068. Not sure when we'll reconsolidate all the JT branches, let alone get it into master.

**Comment by pomalley** [comment]
This is now merged to master.
