### ISSUE TITLE
ADC process readback returns numpy bool for noPllLatch

### ISSUE THREAD

**Issue by pomalley** [martinisgroup/servers#79]
This line: https://github.com/martinisgroup/servers/blob/master/GHzDACs/Cleanup/adc.py#L1055

returns a numpy bool. Here's what I get when I print the type:

```
2015-03-28 17:34:37-0700 [ServerProtocol,client] <type 'numpy.bool_'>
```

I don't know at what point this broke.

**Comment by pomalley** [comment]
It's easily fixable by casting it to `bool`.

**Comment by DanielSank** [comment]
This possibly broke when we made `types.py` less random. Now you get real errors instead of inconsistent unexpected behavior.

That sentence hurt me.

**Comment by pomalley** [comment]
Indeed, this was the error message:
```
Error: (0) TypeError("No LabRAD type for: True (type <type 'numpy.bool_'>)",) [p
ayload=None]
```

**Comment by DanielSank** [comment]
This is more or less a bug in pylabrad, given that we're officially supporting numpy types. Will fix presently.

**Comment by DanielSank** [comment]
Hey, @maffoo, I just went to fix this and I'm a bit puzzled.

**Comment by DanielSank** [comment]
@pomalley proposed fix has been submitted in the pylabrad repo.

**Comment by pomalley** [comment]
Saw that, thanks.

**Comment by pomalley** [comment]
I believe this one is fixed now.
