### ISSUE TITLE
Document GHzDAC calibration procedure.

### ISSUE THREAD

**Issue by pomalley** [martinisgroup/servers#83]
Since @JulianSKelly and I changed the GHzDAC calibration stuff around, there is no longer an interactive script to calibrate the boards. Today Rami wanted to calibrate the boards and I had completely forgotten how we actually do that now. We should document this so that other people know what to do!

**Comment by DanielSank** [comment]
+1

I can't figure out how to calibrate the boards on Jules. This needs to happen asap.

**Comment by DanielSank** [comment]
@pomalley @JulianSKelly please do this as soon as possible. This is a lab-wide problem.

**Comment by pomalley** [comment]
To get you going today:

>>> import servers.ghzdac_cal.GHz_DAC_calibrate as gc
>>> gc.calibrate_iq(cxn, ['Vince DAC 11'])
>>> # or if you want to do all the boards in one go:
>>> gc.calibrate_iq(cxn, gc.find_microwave_dacs(cxn))

**Comment by DanielSank** [comment]
Thank you, Peter!

By the way, I note that the option to not use the microwave switch was not used here. I'll add that in.
